### ISSUE TITLE
"update-grub" fatal error

### ISSUE THREAD

**Issue by WynterFoxx** [sharkwouter/vaporos#1]
Installation runs smoothly until it tries to update grub, at which point it fails and I'm unable to continue the installation.

**Comment by sharkwouter** [comment]
That's odd. I'd like to look into that, but before I can do could you answer the following questions?:
- Which ISO did you download? Which version of VaporOS? Or did you build it yourself?
- Is this a BIOS or UEFI system?
- Do you know if secure boot is enabled?

Now I think about it, I may have seen this issue last week when I was installing a different version of Debian. The workaround for me back then was to install in legacy mode instead of UEFI or EFI mode.

**Comment by sharkwouter** [comment]
![VirtualBox_vaporos_16_08_2019_04_08_48](https://user-images.githubusercontent.com/5042659/63138687-ad6f3400-bfdb-11e9-8564-3656e65b2392.png)

Does it look like this?

**Comment by WynterFoxx** [comment]
> 
> 
> That's odd. I'd like to look into that, but before I can do could you answer the following questions?:
> 
>     * Which ISO did you download? Which version of VaporOS? Or did you build it yourself?
> 
>     * Is this a BIOS or UEFI system?
> 
>     * Do you know if secure boot is enabled?
> 
> 
> Now I think about it, I may have seen this issue last week when I was installing a different version of Debian. The workaround for me back then was to install in legacy mode instead of UEFI or EFI mode.

- I downloaded the VaporOS-2.195.iso

- My system is UEFI

- Secure Boot is disabled

It does seem likely that the issue is due to me using UEFI. I was able to find a workaround involving aborting the installation at the point where update-grub fails, booting up the drive with SteamOS on it, using command-line grub to boot up SteamOS and then fixing some typo in grub2's uefi firmware, but I wasn't able to get it to work unfortunately..

**Comment by WynterFoxx** [comment]
> 
> 
> ![VirtualBox_vaporos_16_08_2019_04_08_48](https://user-images.githubusercontent.com/5042659/63138687-ad6f3400-bfdb-11e9-8564-3656e65b2392.png)
> 
> Does it look like this?

No, unfortunately. I lost the screenshot I had, but the screen states something along the lines of "executing 'update-grub' failed. This is a fatal error."

**Comment by WynterFoxx** [comment]
I was able to workaround the issue by installing SteamOS up to the point where update-grub fails, pressing ctrl+alt+f2 to open up a terminal, and inputting `chmod -x cdrom/etc/grub.d/30_uefi-firmware`
