### ISSUE TITLE
login issue

### ISSUE THREAD

**Issue by HarkTu** [sharkwouter/vaporos#2]
just install it for stress test. after install i couldn't login my steam account.
found some discussions for issue, look like an old problem which still exist.
https://steamcommunity.com/groups/steamuniverse/discussions/1/1760230157499060571/
https://steamcommunity.com/groups/steamuniverse/discussions/0/1760230157500009899/

**Comment by sharkwouter** [comment]
This should be fixed by now, but VaporOS is also no longer supported.
