### ISSUE TITLE
VaporOs on 32 bit hardware

### ISSUE THREAD

**Issue by pams95** [sharkwouter/vaporos#3]
hello,
I want to use VaporOs to stream my pc screen on a 32bit old pc.
I need to know if and how vaporos can run on 32bit hardware.
thanks
pams_

**Comment by sharkwouter** [comment]
Unfortunately, VaporOS cannot run on 32 bit hardware. Are you sure the hardware does not support 64 bit?

**Comment by pams95** [comment]
I am sure this is an old computer i verified architecture and it's i386.
Thank you for the fast answer.

**Comment by sharkwouter** [comment]
I'll close this for now, as there is not really a way to fix this. Sorry about that
