### ISSUE TITLE
Is VaporOS still maintened and active ?

### ISSUE THREAD

**Issue by nonobio** [sharkwouter/vaporos#4]
Hi,

I've just tried SteamOS, its great but i have some issues with it, so i would try alternative.

VaporOS is attractive (i nedd Kodi too), but is it still active ?

Thanks

**Comment by sharkwouter** [comment]
Unfortunately, since VaporOS is build on top of SteamOS and SteamOS is no longer getting updates, VaporOS is not an active project anymore. I can recommend GamerOS if you're looking for a more up-to-date SteamOS like experience.

**Comment by nonobio** [comment]
Hi,

Thanks for your reply. 

I tried GamerOS but i had a black screen and it doesn't support double boot...

I undestand that SteamOS is in standby for now i finally installed it in dualboot with LibreElec and it works fine.
I just had to customize my resolution for my old TV.

I just have missing functions like no volume control with keyboard volume buttons and no support for Xbox one controllers "wirelessly".

If you know simple solutions to this for SteamOS, i'm interesting, but i can leave without them ;) .

Maybe VaporOS add this functions ? If yes, maybe i could try it...

**Comment by sharkwouter** [comment]
For Xbox One controller support you could install this: https://github.com/medusalix/xow

I have tried recreating SteamOS on a different version of Debian before, but I didn't quite get it working. If you're interested, you could try your hand at it. My work on it can be found here: https://github.com/sharkwouter/vaporos-buster

If you want to add something to VaporOS feel free to try it. You can find some old tutorials I made here: https://www.youtube.com/watch?v=i12nD9EKoB8&list=PLEsn6Rtpq7Pk9N43FjQVpRlXlPqt2mofe

**Comment by sharkwouter** [comment]
To add to the previous comment. I also wrote the following documentation on working with VaporOS on the wiki of this repo: https://github.com/sharkwouter/vaporos/wiki

**Comment by sharkwouter** [comment]
If you go through with this you may run into the issue that the VaporOS repo is not up at the moment. I can't fix this at the moment. In July I would be able to do this.

**Comment by nonobio** [comment]
i will stay with SteamOS for now as it works fine.
Thanks for the link xow, maybe i will try it but it seems it can have some issues...

have a nice day :)
